export enum UserRole {
  ROLE_STUDENT = "ROLE_STUDENT",
  ROLE_TEACHER = "ROLE_TEACHER",
  ROLE_ADMIN = "ROLE_ADMIN",
  ROLE_NEW_TEACHER = "ROLE_NEW_TEACHER",
  ROLE_HIDDEN_TEACHER = "ROLE_HIDDEN_TEACHER",
  ROLE_MANAGER = "ROLE_MANAGER",
}

export enum PhoneNumberType {
  PHONE = "PHONE",
  WHATSAPP = "WHATSAPP",
}
